name: Compile
on:
  release:
    types: [published]
jobs:
  compile:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - macOS-13
          - macOS-14
          - macOS-15
          - windows-2019
          - windows-2022
          - windows-2025
        version:
          - '1.10'
        arch:
          - 'x64'
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: julia-actions/setup-julia@4c0cb0fce8556fdb04a90347310e5db8b1f98fb9 # v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1 # latest
      - name: Compile
        run: julia --color=yes --project=@. -e 'using CompileMRI; compile()'
      - name: Get Version
        run: echo "::set-output name=version::$(julia --project=@. -e 'using CompileMRI; println(CompileMRI.mritools_version())')"
        id: version
      - name: Compress Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo "ZIP_ENDING=tar.gz" >> $GITHUB_ENV
          echo "ZIP_TYPE=gzip" >> $GITHUB_ENV
          mv compiled mritools_${{ matrix.os }}_${{ steps.version.outputs.version }}
          tar -vczf mritools_${{ matrix.os }}_${{ steps.version.outputs.version }}.tar.gz mritools_${{ matrix.os }}_${{ steps.version.outputs.version }}
      - name: Compress Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "ZIP_ENDING=zip" >> $env:GITHUB_ENV
          echo "ZIP_TYPE=zip" >> $env:GITHUB_ENV
          Compress-Archive -Path 'compiled/*' -DestinationPath 'mritools_${{ matrix.os }}_${{ steps.version.outputs.version }}.zip'
      - name: Upload release
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./mritools_${{ matrix.os }}_${{ steps.version.outputs.version }}.${{ env.ZIP_ENDING }}
          asset_name: mritools_${{ matrix.os }}_${{ steps.version.outputs.version }}.${{ env.ZIP_ENDING }}
          asset_content_type: application/${{ env.ZIP_TYPE }}
